apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.13.2
  volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion 
  nodeSets:
  - name: default
    count: 1
    config:
      node.roles: ["master", "data", "ingest"]
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 30Gi
    podTemplate:
      spec:
        containers:        
        - name: elasticsearch
          readinessProbe:
              exec:
                command:
                - bash
                - -c
                - /mnt/elastic-internal/scripts/readiness-probe-script.sh
              failureThreshold: 3
              initialDelaySeconds: 45
              periodSeconds: 3
              successThreshold: 1
              timeoutSeconds: 45
          env:
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx2048m
            #- name: ELASTICSEARCH_URL
             # value: http://quickstart-es-http.default.svc:9200     
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "2500m"
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists   