apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart-logstash
spec:
  version: 8.13.2
  count: 1
  elasticsearchRefs:
    - name: quickstart
      clusterName: qs  
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044      
  volumeClaimTemplates:
    - metadata:
        name: logstash-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 10Gi        
 # podTemplate:
  #  spec:
    #  tolerations:
    #    - effect: NoSchedule
    #      key: node-role.kubernetes.io/master
    #      operator: Exists