apiVersion: v1
kind: Service
metadata:
  name: agify-service
spec:
  selector:
    app: agify-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agify-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agify-service
  template:
    metadata:
      labels:
        app: agify-service
    spec:
      containers:
        - name: agify-service
          image: camranjuntinase/sa_p2:agify
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: genderize-service
spec:
  selector:
    app: genderize-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genderize-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genderize-service
  template:
    metadata:
      labels:
        app: genderize-service
    spec:
      containers:
        - name: genderize-service
          image: camranjuntinase/sa_p2:genderize
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: public-service
spec:
  selector:
    app: public-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-service
  template:
    metadata:
      labels:
        app: public-service
    spec:
      containers:
        - name: public-service
          image: camranjuntinase/sa_p2:mixedIOv3
          ports:
            - containerPort: 4000
